---

- hosts: flask-app-servers


  tasks:

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "Install GnuPG and GIT and Nginx"
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: copy tarball to host
      copy:
        src: /home/leej92/skbx_devops_diploma/flask_project
        dest: /root

    - name: build container image
      docker_image:
        name: my_flask_app:v0.1
        build:
          path: /root/flask_project/app/Dockerfile
          source: build
        state: present

    - name: Launch docker container
      docker_container:
        name: my_flask_app:v0.1
        image: my_flask_app:v0.1
        state: started
        auto_remove: true
        ports:
          - "5000:5000"
